# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5181164d9431387dc98d13c97a789b4267bb33e851798fdd92ee82586a2f2bec4779383972e227aad2b5f51aa463a26c1c063c550587f45258f528f923aabd1

test:
  secret_key_base: 8849a91ff1ca4ec12565e0359abaf8ae70c578ce8f31c30e50db530d8944da422aebd381dbbedd83a82f96edf35ced3f6d9b1ca39111f4143cdbe1be5505371f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
